### ISSUE TITLE
Wrong item removed from hand.

### ISSUE THREAD

**Issue by Worive** [shinyafro/DirtRestrict#1]
Situation:

Being full inventory with a DE Magnet enabled.
Break the chest cart.
TNT Cart dropped.
On pick up (by magnet) but full inventory, item in hand (Staff of Power that broke the chest cart) is wiped.

**Comment by Worive** [comment]
I'm still trying to see if it's possible to reproduce. Without success at the moment

**Comment by shinyafro** [comment]
might be when the item is being filtered by the SOP maybe? still need to figure out how it is occuring to prevent it.

**Comment by Worive** [comment]
he broke a chest cart. It's not a block so it shouldn't be able to be filtered as entity because he just did dmg. And the issue only did 1 warning message about banned item, not 2 :thinking:

**Comment by Worive** [comment]
https://github.com/Dirt-Craft/DirtRestrict/blob/master/src/main/java/net/dirtcraft/dirtrestrict/Handlers/Restrictions/OwnershipHandler.java#L149

Causing loss when droping item directly from inventory. (Wiping hand without checking)

**Comment by Worive** [comment]
Fixed in https://github.com/Dirt-Craft/DirtRestrict/commit/98a902a9e9a36fbdc2a259348a148718ab38c6f6
